server:
  port: 8083

spring:
  profiles:
    active: develop
  datasource:
    url: jdbc:postgresql:piggybank
    driverClassName: org.postgresql.Driver
    username:
    password:
  jpa:
    datasource-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

kafka:
  bootstrapServerURL: 'localhost:29092'
  topics:
    receiptExcelFileStorageTopicName: "file-storage-service.receipt-excel.v1"
    receiptImageFileStorageTopicName: "file-storage-service.receipt-image.v1"

storage:
  fileGroups:
    RECEIPT_EXCEL:
      readingScheduleCron: "*/5 * * * * *"
      sourceFolderPath: "/home/tomek/Documents/projects/storage/receipt_excel/source"
      destinationFolderPath: "/home/tomek/Documents/projects/storage/receipt_excel/stored"
      errorFolderPath: "/home/tomek/Documents/projects/storage/receipt_excel/errors"
      allowedFileExtensions: ["xlsx"]
    RECEIPT_IMAGE:
      readingScheduleCron: "*/5 * * * * *"
      sourceFolderPath: "/home/tomek/Documents/projects/storage/receipt_image/source"
      destinationFolderPath: "/home/tomek/Documents/projects/storage/receipt_image/stored"
      errorFolderPath: "/home/tomek/Documents/projects/storage/receipt_image/errors"
      allowedFileExtensions: [ "jpg", "jpeg", "png" ]